all:
  children:
    switches:
      hosts:
        sw1:
          hostname: SW1
          mgmt_ip: 10.0.0.11
        sw2:
          hostname: SW2
          mgmt_ip: 10.0.0.22
        sw3:
          hostname: SW3
          mgmt_ip: 10.0.0.13  
  vars:
    ansible_connection: local
