all:
  children:
    switches:
      hosts:
        sw1:
          hostname: SW1
          mgmt_ip: 10.0.0.11
        sw2:
          hostname: SW2
          mgmt_ip: 10.0.0.12
  vars:
    ansible_connection: local
